log_level = "warn"
outputs = { Targets = ["eDP-1", "DP-1"] }
position = "Top"
app_launcher_cmd = "wofi"

[modules]
left = [ [ "Workspaces" ] ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [  "Tray", "Clock", "Privacy", "Settings" ] ]

[workspaces]
enable_workspace_filling = true

[[CustomModule]]
name = "appLauncher"
icon = "ó±—¼"
command = "wofi"

[window_title]
truncate_title_after_length = 100

[settings]
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "iwgtk"
bluetooth_more_cmd = "blueman-manager"

[appearance]
style = "Solid"
font_name = "JetBrainsMono NF"

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"
workspace_colors = [ "#7aa2f7", "#9ece6a" ]
special_workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"

